package sk.styk.martin.bakalarka.compare.processors;

/**
 * Created by Martin Styk on 07.02.2016.
 */
public enum SimilarityType {
    NOT_SIMILAR,
    SIMILAR_SAME_CERTIFICATE_SAME_VERSION,
    SIMILAR_SAME_CERTIFICATE_DIFFERENT_VERSION,
    SIMILAR_SAME_CERTIFICATE_UNDETERMINED_VERSION,
    SIMILAR_DIFFERENT_CERTIFICATE_SAME_VERSION,
    SIMILAR_DIFFERENT_CERTIFICATE_DIFFERENT_VERSION,
    SIMILAR_DIFFERENT_CERTIFICATE_UNDETERMINED_VERSION,
    SIMILAR_UNDETERMINED_CERTIFICATE_SAME_VERSION,
    SIMILAR_UNDETERMINED_CERTIFICATE_DIFFERENT_VERSION,
    SIMILAR_UNDETERMINED_CERTIFICATE_UNDETERMINED_VERSION
}
